# Generated by Django 4.0.4 on 2022-05-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('coursecode', models.CharField(default='default', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('department_name', models.CharField(max_length=63)),
                ('semester_name', models.CharField(max_length=63)),
                ('semester_type', models.CharField(max_length=63, null=True)),
                ('ects', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('outcome', models.TextField(null=True)),
                ('structure', models.TextField(null=True)),
                ('assessment', models.TextField(null=True)),
                ('methods', models.TextField(null=True)),
                ('teaching_language', models.CharField(max_length=63)),
                ('has_prerequisite', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.course')),
                ('semesterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.semesters')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id1', to='courseselect.course')),
                ('to_course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='courseselect.course')),
            ],
        ),
    ]
