# Generated by Django 4.0.4 on 2022-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehasprerequisite',
            name='parallel_enrollment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
