# Generated by Django 4.0.4 on 2022-05-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursecode',
            field=models.CharField(default='default', max_length=255, primary_key=True, serialize=False),
        ),
    ]
