# Generated by Django 4.0.4 on 2022-05-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0002_headrequirements_requiredcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHasLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.course')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('head_req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.headrequirements')),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.label')),
            ],
        ),
        migrations.DeleteModel(
            name='RequiredCourses',
        ),
        migrations.AddField(
            model_name='coursehaslabel',
            name='label_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.label'),
        ),
    ]
