# Generated by Django 4.0.4 on 2022-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0002_alter_course_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester_type',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
