# Generated by Django 4.0.4 on 2022-05-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0003_coursehaslabel_label_subrequirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='calender_semester',
            field=models.IntegerField(null=True),
        ),
    ]
