# Generated by Django 4.0.4 on 2022-04-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0004_alter_coursesemester_semesterid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursehasprerequisite',
            old_name='fromID',
            new_name='fromid',
        ),
        migrations.RenameField(
            model_name='coursehasprerequisite',
            old_name='toID',
            new_name='toid',
        ),
        migrations.RenameField(
            model_name='coursesemester',
            old_name='courseID',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='coursesemester',
            old_name='semesterID',
            new_name='semesterid',
        ),
    ]
