# Generated by Django 4.0.4 on 2022-05-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0005_rename_fromid_coursehasprerequisite_fromid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=63)),
            ],
        ),
        migrations.AlterField(
            model_name='coursesemester',
            name='semesterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.semesters'),
        ),
    ]
