# Generated by Django 4.0.4 on 2022-04-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='text',
        ),
    ]
