# Generated by Django 4.0.4 on 2022-04-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0002_remove_course_pub_date_remove_course_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterID', models.CharField(max_length=63)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseselect.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id1', to='courseselect.course')),
                ('toID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='courseselect.course')),
            ],
        ),
    ]
