# Generated by Django 4.0.4 on 2022-04-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseselect', '0003_coursesemester_coursehasprerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesemester',
            name='semesterID',
            field=models.IntegerField(),
        ),
    ]
